diagnostic_aggregator:
  analyzers:
    sensors:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Sensors
      find_and_remove_prefix: 'DataProcessingNode: '
      timeout: 5.0
      num_items: 2
